### PR TITLE
terminal support helpers

### PR DESCRIPTION
**Pull request by patrick330602**
1. sudo.ps1 for auotmatically installing AppX;
2. winpwsh-exe to use powershell in pengwin-setup.

### CODE REVIEW

**Comment by WSLUser** [comment]
Is this ready to be merged?

**Comment by crramirez** [comment]
Yes, but it won't be merged yet. This is there to support Windows Terminal installation via appx, but this approach has issues with dependencies so we decided, for now, to disable this option and simply redirect the user to Microsoft Store.

Also, WSLU 3 will include part of this functionality.

**Comment by crramirez** [comment]
@WSLUser I am wondering about why you asked. Do you see any use of this apart of what I mentioned here?

**Comment by WSLUser** [comment]
Mostly this has been here awhile and looked ready

**Comment by crramirez** [comment]
@WSLUser I removed part of it as it is included in wslu 3 and merging. Then each call to power shell in pengwin-setup will call this

**Pull request merged**
